### ISSUE TITLE
Watch for DAL update with dark mode support

### ISSUE THREAD

**Issue by sveetch** [emencia/django-blog-lotus#46]
**Is your feature request related to a problem? Please describe.**
Current django-autocomplete-light (DAL) version (3.9.4) is not yet compatible Django admin and dark mode.

So for now, we included the following patch in `templates/admin/lotus/article/change_form.html` :

https://github.com/yourlabs/django-autocomplete-light/pull/1308

**Describe the solution you'd like**
A new DAL release which should include the dark mode support from PR1308. Once released we will upgrade requirement to this new version then remove the backported fix from "change_form" template.

**Describe alternatives you've considered**
Keeping the patch in the template, but if DAL does not update anymore, it should be removed from requirements because we won't attach Lotus to an unmaintained application.

**Comment by daweedm** [comment]
@sveetch I have the same issue and I don't understand why the fix is not yet included in the 3.9.4 release as it was merged. Should we use a rc release instead ?

**Comment by sveetch** [comment]
Note: The 3.9.5-rc6 has fixed dark mode problem and is working well, monitoring the final 3.9.5 release to upgrade dependency and removing the temporary hack fix from `admin/lotus/article/change_form.html` (the `style` block).

**Comment by sveetch** [comment]
DAL 3.9.5 is out and has been validated to fix problem which leaded to temporary hack, it's time to upgrade and cleanup things from hack.

**Comment by sveetch** [comment]
Upgraded in 0.5.3-pre.8
