### ISSUE TITLE
Cannot access images in documentation overview

### ISSUE THREAD

**Issue by Sam-prog-sudo** [emencia/django-blog-lotus#47]
Image is not accessible: only preview is shown.

1. Go to [documentation](https://django-blog-lotus.readthedocs.io/en/latest/overview.html)
2. Click on any image in `#demonstration`

Expected behavior:
On click, browser should redirect to full size image.

Possible solution:
Provide link to `/docs/_static/demo/<an_image>`

**Comment by sveetch** [comment]
It has been fixed in 0.5.1-pre.4, it will be published with the 0.5.1 release
